version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: chat_pg
    command: -p 2345
    env_file: .env
    expose:
      - '2345'

  redis:
    image: redis:7.2.2-alpine
    container_name: chat_redis
    command: --port 9737
    volumes:
      - ./docker-data/db/redis:/data
    expose:
      - '9737'

  web:
    build: .
    container_name: chat
    command: ./bin/rails server -b 0.0.0.0 -p 4000
    env_file: .env
    environment:
      RAILS_ENV: development
    volumes:
      - .:/chat_app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
