version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: pg
    environment:
      - POSTGRES_DB=chat_app_development
      - POSTGRES_USER=san
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '2345:5432'

  redis:
    image: redis:7.2.2-alpine
    container_name: redis
    command: --port 9737
    ports:
      - '9737:9737'
    volumes:
      - ./docker-data/db/redis:/data

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 4000
    volumes:
      - .:/chat_app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
