default: &default
  adapter: postgresql
  encoding: unicode
  username: alex
  password: alex
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 2345
  # host: localhost
  # port: 5432

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app_production
  username: alex
  password: alex
